---
- hosts: default
  roles:
    - role: dev-sec.os-hardening
      become: yes
      become_user: root
      become_method: sudo
      vars:
        os_auth_allow_homeless: true
    - role: dev-sec.ssh-hardening
      become: yes
      become_user: root
      become_method: sudo
      vars:
        ssh_use_pam: true
        ssh_allow_agent_forwarding: true
        sftp_enabled: false
        ssh_host_key_files: ["/etc/ssh/ssh_host_ed25519_key", "/etc/ssh/ssh_host_rsa_key"]
        ssh_macs:
          - hmac-sha2-512-etm@openssh.com
          - hmac-sha2-256-etm@openssh.com
          - umac-128-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-256
        ssh_ciphers:
          - chacha20-poly1305@openssh.com
          - aes256-gcm@openssh.com
          - aes128-gcm@openssh.com
          - aes256-ctr
          - aes192-ctr
          - aes128-ctr
        ssh_kex:
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
